name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure sccache
      uses: ./
      with:
        cache-key: sccache-ubuntu-latest

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose


  build-with-key:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure sccache
      uses: ./
      with:
        cache-key: sccache-ubuntu-latest
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose


